apiVersion: v1
kind: Service
metadata:
  name: pyserver-service
spec:
  selector:
    app: pyserver
  type: ClusterIP
  ports:
  - name: pyserver-service
    port: 80
    targetPort: 5000
    protocol: TCP